name = input("Enter your name: ")
phone = input("Enter your phone number: ")
age = input("Enter your age: ")
city = input("Enter your city: ")
contact = input("Enter your contact number: ")
address = input("Enter your address: ")
blood_group = input("Enter your blood group: ")
bloodsugar = input("Enter your blood sugar level: ")
pressure = input("Enter your blood pressure: ")
print("USER DETAILS:")
print("Name:", name)
print("Phone Number:", phone)
print("Age:", age)
print("City:", city)
print("Contact Number:", contact)
print("Address:", address)
print("Blood Group:", blood_group)
print("Blood Sugar Level:", bloodsugar)
print("Blood Pressure:", pressure)