name = input("Enter your name: ")
phone = input("Enter your phone number: ")
age = input("Enter your age: ")
city = input("Enter your city: ")
contact = input("Enter your contact number: ")
print("USER DETAILS:")
print("Name:", name)
print("Phone Number:", phone)
print("Age:", age)
print("City:", city)
print("Contact Number:", contact)